name: Checkstyle and SpotBugs

on:
  workflow_dispatch:
    inputs:
      java-version:
        description: 'Java version'
        required: true
        default: '11'
        type: choice
        options: ['11', '17']

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ github.event.inputs['java-version'] }}

    - name: Build and analyze with Checkstyle
      run: |
        mvn checkstyle:check
      working-directory: app/java

    - name: Build and analyze with SpotBugs
      run: |
        mvn compile com.github.spotbugs:spotbugs-maven-plugin:check
      working-directory: app/java
